export const MAX_TEST_QUESTIONS = 5;
export const MAX_COVER_LETTERS = 5;
export const MAX_COVER_LETTERS_TABS = 5;
export const MAX_INTERVIEW_PHASE_1_MESSAGES = 10;
export const MAX_FILE_SIZE_KB = 200; // 200KB
export const MAX_FILE_NUM_PAGES = 2;
export const MAX_FILE_TEXT_LENGTH = 10_000;
export const IS_PRO_ENABLED = true;
export const MAX_APPLICANTS_WO_PRO = 1;
export const MAX_APPLICANTS = 5;
export const MAX_APPLICATIONS_WO_PRO = 3;
export const MAX_APPLICATIONS = 20;
